name: Build and Release

on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Fetch all history for all tags and branches
      run: |
        git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch --prune --unshallow
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore tools
      run: dotnet tool restore

    - name: Build
      id: build
      run: dotnet cake --target=Package
      
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      if: github.event_name == 'push'
      with:
        artifacts: ./artifacts/*.zip
        commit: ${{ github.sha }}
        tag: ${{ steps.build.outputs.version }}
      


